FROM node:latest
FROM redis:latest

#Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app
RUN npm install

#Bundle app source to docker image
COPY ./usr/src/app

EXPOSE 8090

CMD ["npm", "start"]